[package]
name = "UniswapV2"
version = "1.0.0"

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
UniswapV2 = "0xe43e88c9c01cd2515367a3c7a74cbfa5817c965910f9a9ab91c65f72a2b5a47f"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "8399cd1c7b9662d3a6a09c28363c5f66f0839c41" # aptos-cli-v0.3.1a
subdir = "aptos-move/framework/aptos-framework"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "8399cd1c7b9662d3a6a09c28363c5f66f0839c41" # aptos-cli-v0.3.1a
subdir = "aptos-move/framework/move-stdlib"